### ISSUE TITLE
Company Name

### ISSUE THREAD

**Issue by Steele1224** [Steele1224/SC#2]
Create company name and mission statement.

**Comment by Hermsmegerms** [comment]
Some ideas i have come up with for names
- Runed Games
- Spell Sword Software 
- AdventureCore
- Mobius Games (cool ideas for an icon for this one bassed on a mobius strip)
- Hermott Games (bassed on our last names)

I have had this page open since i started work at 830 just jotting down what popped in my head

**Comment by Steele1224** [comment]
I have about ten jotted down on my home computer will update when I am able. Also Hermott could just be Hermit Games\Software\Productions\Studios. Sounds the same.

**Comment by Hermsmegerms** [comment]
Reason i liked the O instead of the I is hermit games already exists. by combining our names and keeping the o its different enough to not be a problem

**Comment by Steele1224** [comment]
1.  **Flash Fire Studios**
2.  Crazy Tortoise Productions
3.  Wagon Wheel Software
4.  **Static Eclipse Software**
5.  Mad Hops Productions
6.  Dad’s Watch Productions
7.  Dex Realms Software
8.  Steel Productions
9.  Tornado Studios
10. **Doughnut Knight Software**

I made a few some are trash but I do like a few of these

**Comment by Hermsmegerms** [comment]
I love Dad's watch

**Comment by knoblett** [comment]
Definitely 'no' to `Runed Games`. Sounds too much like `Ruined Games`, which definitely give bashing potential if y'all ever get haters.

I like Wagon Wheel for the hilarity, and Dad's Watch. But that's probably not the best idea for a studio name.

I'd go with something short and easy. I mean Bethesda is the name of the city they're in. BioWare is really short. EA has a good abbreviation. Is a 1-word name possible? Maybe SteelWare? idk. I'm bad at names.

**Comment by Hermsmegerms** [comment]
Bathesda is actually bassed out of Rockford. lol

Could be somthing like SH! studios. Steel Herman studios or Scott Herman studios. Just SH!

**Comment by Hermsmegerms** [comment]
SH! 
Was what we decided on
